version: '2'
services:    
    hogwhat:
        container_name: hogwhat
        build: ..
        command: /usr/bin/supervisord -n
        ports:
        - "8002:8000"
        volumes:
        - ..:/apisrv
        image: heejun8609/hogwhat:latest