version: '2'
services:    
    hogwhat_dev:
        container_name: hogwhat_dev
        build: ..
        command: install/docker-entrypoint.sh
        ports:
        - "8002:8000"
        volumes:
        - ..:/apisrv
        image: heejun8609/hogwhat:latest
        